package dam2.dam2.ejemploHibernate;
// Generated 9 dic 2024, 10:27:08 by Hibernate Tools 6.5.1.Final


import java.sql.Timestamp;

/**
 * Pedidos generated by hbm2java
 */
public class Pedidos  implements java.io.Serializable {


     private Integer id;
     private Proveedores proveedores;
     private Usuarios usuarios;
     private Timestamp fecha;
     private double total;
     private String estado;

    public Pedidos() {
    }

	
    public Pedidos(Usuarios usuarios, double total) {
        this.usuarios = usuarios;
        this.total = total;
    }
    public Pedidos(Proveedores proveedores, Usuarios usuarios, Timestamp fecha, double total, String estado) {
       this.proveedores = proveedores;
       this.usuarios = usuarios;
       this.fecha = fecha;
       this.total = total;
       this.estado = estado;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Proveedores getProveedores() {
        return this.proveedores;
    }
    
    public void setProveedores(Proveedores proveedores) {
        this.proveedores = proveedores;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public Timestamp getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Timestamp fecha) {
        this.fecha = fecha;
    }
    public double getTotal() {
        return this.total;
    }
    
    public void setTotal(double total) {
        this.total = total;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


