package dam2.dam2.ejemploHibernate;
// Generated 9 dic 2024, 10:27:08 by Hibernate Tools 6.5.1.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Productos generated by hbm2java
 */
public class Productos  implements java.io.Serializable {


     private Integer id;
     private Categorias categorias;
     private String nombre;
     private int stock;
     private Integer cantidad;
     private double precio;
     private String descripcion;
     private Boolean activo;
     private Set lineaVentases = new HashSet(0);

    public Productos() {
    }

	
    public Productos(String nombre, int stock, double precio) {
        this.nombre = nombre;
        this.stock = stock;
        this.precio = precio;
    }
    public Productos(Categorias categorias, String nombre, int stock, Integer cantidad, double precio, String descripcion, Boolean activo, Set lineaVentases) {
       this.categorias = categorias;
       this.nombre = nombre;
       this.stock = stock;
       this.cantidad = cantidad;
       this.precio = precio;
       this.descripcion = descripcion;
       this.activo = activo;
       this.lineaVentases = lineaVentases;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Categorias getCategorias() {
        return this.categorias;
    }
    
    public void setCategorias(Categorias categorias) {
        this.categorias = categorias;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getStock() {
        return this.stock;
    }
    
    public void setStock(int stock) {
        this.stock = stock;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(double precio) {
        this.precio = precio;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Boolean getActivo() {
        return this.activo;
    }
    
    public void setActivo(Boolean activo) {
        this.activo = activo;
    }
    public Set getLineaVentases() {
        return this.lineaVentases;
    }
    
    public void setLineaVentases(Set lineaVentases) {
        this.lineaVentases = lineaVentases;
    }




}


